# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
