# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160917_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to='portal.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ta_courses',
            field=models.ManyToManyField(related_name='tas', to='portal.Course'),
        ),
    ]
