# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160926_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=255)),
                ('num_recommendations', models.IntegerField(default=0)),
            ],
        ),
    ]
