# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_courserecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allowed_courses',
            field=models.ManyToManyField(related_name='roster', to='portal.Course'),
        ),
    ]
